CRUD/__init__.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

import os

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
# for csrf protection
from flask_wtf.csrf import CsrfProtect

from config import config

# for vue.js, allowing for ${} delimiter in html files with jinja2 markup
class CustomFlask(Flask):
    jinja_options = Flask.jinja_options.copy()
    jinja_options.update(dict(
        block_start_string='$$',
        block_end_string='$$',
        variable_start_string='$',
        variable_end_string='$',
        comment_start_string='$#',
        comment_end_string='#$',

    ))

#app = CustomFlask(__name__)

# because we are creating an application instance in create_app()
# there is no global application instance object being passed to these
# extensions below.
# When you have an application instance, you complete the initialization
# of these extensions on the app object by passing the app object to 
# extension.init_app(app), like is done in create_app()

# creating unitialized extensions
csrf = CsrfProtect()
db = SQLAlchemy()


def create_app(config_name):
    """
    Create an application instance
    """
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    
    #bootstrap.init_app(app)
    #mail.init_app(app)
    #moment.init_app(app)
    db.init_app(app)

    # using this context manager block to execute db.create_all(), which
    # maps the table to the db, within the context of the application 
    # instance (app) being pushed or activated in the current application 
    # context using app_context(). In other words, SQLAlchemy now knows what 
    # the current app is. If we do not use this, we get a RunTimeError of:
    # application not registered on db instance and no application bound to
    # current object.
    with app.app_context():
        db.create_all()

    csrf.init_app(app)



    #login_manager.init_app(app)
    #pagedown.init_app(app)
    
    #if not app.debug and not app.testing and not app.config['SSL_DISABLE']:
    #    from flask_sslify import SSLify
    #    sslify = SSLify(app)
    
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    #from .auth import auth as auth_blueprint
    #app.register_blueprint(auth_blueprint, url_prefix='/auth')
    
    #from .api_1_0 import api as api_1_0_blueprint
    #app.register_blueprint(api_1_0_blueprint, url_prefix='/api/v1.0')
    
    return app

CRUD/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

CRUD/main/views.py
from . import main
from .. import db

from flask import render_template, jsonify, url_for, request, redirect, current_app, abort

from ..database import Person
from sqlalchemy import select, or_, and_

import re

from query_handler import query_handler

# PAGINATE_BY is a module constant that indicates how many should be on
# each page
PAGINATE_BY = 10

from flask.ext.login import login_required


@main.route("/")
def index():
    return render_template("index.html")


from flask.ext.login import current_user



@main.route("/addperson/", methods=["GET", "POST"])
def addperson():
    print(request)
    if request.method == "POST":
        #print(request.get_data())
        #print(request.form)
        print(request.get_json)

	form_data = request.get_json()
        people = Person(
            firstname=form_data["firstname"],
            lastname=form_data["lastname"],
            dob=form_data["DOB"],
            zipcode=form_data["postalCode"]
        )
        db.session.add(people)
        db.session.commit()
        display_entries = {}
        # count is just acting as a key for the value, which is every person
        # dict row entry representation
        count = 0
        for person in db.session.query(Person).all():
            print person.__dict__
            db_dict = person.__dict__
            del db_dict['_sa_instance_state']
            display_entries[count] = db_dict
            count += 1
	
	return render_template("addperson.html")

    return render_template("addperson.html")


@main.route("/successconfirm/")
def success_confirm():
    return render_template("successconfirm.html")


# API GET endpoint for people
@main.route("/listpeople/")
def listpeople():
    print(request)

    page_num = request.args.get('page')

    results_slice_stop = (PAGINATE_BY * int(page_num))
    results_slice_start = (PAGINATE_BY * (int(page_num) - 1))
    display_entries = {}
    count = 0
    query_results = db.session.query(Person).all()

    # getting query results count to pass to include with server Ajax response
    display_entries = {'results_count': len(query_results)}

    query_results = query_results[results_slice_start:results_slice_stop]

   # for person in session.query(Person).all():
    for person in query_results:
        print person.__dict__
        count += 1
        db_dict = person.__dict__
        del db_dict['_sa_instance_state']
        display_entries[count] = db_dict

    return(jsonify(display_entries))


current_search_query = None


@main.route("/searchpeople", methods=["GET", "POST"])
@main.route("/searchpeople/page/<int:page>")
def searchpeople(page=1):
    print(request)
    # if no search_query in URL will evaluate to None
    search_query = request.args.get('search_for')
    print(search_query)

    print(request.form)

    # for general db display, returns all entries, paginated
    if (search_query is None or search_query == u"") and request.method == "GET":
        print("inside if search_query is None")

        get_all_entries = db.session.query(Person).all()
        count = db.session.query(Person).count()

        print("Total db entries count: {}".format(count))

        # Zero-indexed page
        page_index = page - 1  # page_index is page number - 1 = 0 for zero-based index
        # query object to determine number of enties in total
        # start = 0 X 10 = 0  index of first item displayed
        start = page_index * PAGINATE_BY
        end = start + PAGINATE_BY  # end = 0 + 10 = 10  index of last item displayed
        # total number of pages of content
        total_pages = (count - 1) / PAGINATE_BY + 1
        # this is a boolean statement --> if True, then there's a next page
        has_next = page_index < total_pages - 1
        has_prev = page_index > 0  # this is a boolean statement

        # all_entries = get_all_entries.order_by(Person.lastname)  # order entries by
        # slicing query to only return entries between start and end
        # indices
        all_entries = get_all_entries[start:end]
        return render_template("searchpeople.html",
                               people=all_entries,
                               has_next=has_next,
                               has_prev=has_prev,
                               page=page,
                               total_pages=total_pages
                               )


    people = db.session.query(Person)

    # DELETE request handler
    if request.method == "POST":
	form = request.get_json()
	if "delete_id" in form:
	    person_to_delete = form["delete_id"]
            delete_person_by_id = db.session.query(
                Person).filter_by(id=person_to_delete).delete()
            db.session.commit()
            deleteconfirmation = True
            confirm_message = {
                'delete_confirmation': 'id: {}'.format(person_to_delete)}
            return jsonify(confirm_message)

        else:
            print("making update to entry")
	    
	    # get json form data
	    form = request.get_json()
	    print(form)
	    id = form["db_id"]
	    print(id)

            # checking for values in the submitted form
            if form["firstname"] != '':
                update_dbentry = db.session.query(Person).filter_by(id=id).update(
                    {"firstname": "%s" % (form["firstname"])})

            if form["lastname"] != '':
                update_dbentry = db.session.query(Person).filter_by(id=id).update(
                    {"lastname": "%s" % (form["lastname"])})

            if form["DOB"] != '':
                update_dbentry = db.session.query(Person).filter_by(
                    id=id).update({"dob": "%s" % (form["DOB"])})

            if form["zipcode"] != '':
                update_dbentry = db.session.query(Person).filter_by(id=id).update(
                    {"zipcode": "%s" % (form["zipcode"])})

            # getting updated entry to pass back to Ajax caller, which will
            # pass to vue to update item

            db.session.commit()

            updated_entry = {}
            #vueEntryIndex = request.form["vue_page_index"]
            vueEntryIndex = form["vue_page_index"]
	    
	    updated_entry["entry_vue_page_$index"] = vueEntryIndex

            get_updated_entry = db.session.query(Person).filter_by(id=id)
            for result in get_updated_entry:
                result = result.__dict__
                del result['_sa_instance_state']
                updated_entry[vueEntryIndex] = result

            print(jsonify(updated_entry))
            return jsonify(updated_entry)

    # when page is initially loaded
    # if search_query is None:
    #    return render_template("searchpeople.html")

    else:
        print("SEARCH QUERY")
        # NEW SEARCH QUERY CHECK LOGIC
        # check if there is already a query paramter in the URL with pagination
# use case is if user has paginated through initial returns query results, and then goes to try another search. Search query results will be presented with the most recent page, instead of staring from first results first page in query results.
        # regex to compare current path to original URL route

        current_url = request.path
        print("current_url: {}".format(current_url))
        regex = re.compile(r'/searchpeople/page/[0-9]')
        if regex.match(current_url) is not None and (
                current_search_query != search_query):
            print("regex match")
            # return redirect(url_for('searchpeople',
            # search_query=search_query))
            return redirect('/searchpeople?search_for={}'.format(search_query))

        # END OF NEW SEARCH QUERY CHECK LOGIC

        print("submitting search_query to query_handler....")
        call_query_handler = query_handler(search_query)

        # if no results found, call_query_handler returns True for noresults
        if call_query_handler is None:
            noresult = True
            return render_template("searchpeople.html", noresult=noresult)

        search_results, count = call_query_handler

        # Zero-indexed page
        page_index = page - 1  # page_index is page number - 1 = 0 for zero-based index
        # query object to determine number of enties in total
        # start = 0 X 10 = 0  index of first item displayed
        start = page_index * PAGINATE_BY
        end = start + PAGINATE_BY  # end = 0 + 10 = 10  index of last item displayed
        # total number of pages of content
        total_pages = (count - 1) / PAGINATE_BY + 1
        # this is a boolean statement --> if True, then there's a next page
        has_next = page_index < total_pages - 1
        has_prev = page_index > 0  # this is a boolean statement

        search_results = search_results.order_by(
            Person.lastname)  # order entries by
        # slicing query to only return entries between start and end
        # indices
        search_results = search_results[start:end]

        global current_search_query
        current_search_query = search_query

        display_entries = {'results_count': count}
        for person in search_results:
            print person.__dict__
            count += 1
            db_dict = person.__dict__
            del db_dict['_sa_instance_state']
            display_entries[count] = db_dict

        print("display_entries: ")
        print(display_entries)

        return(jsonify(display_entries))

###############################TEST VIEWS####################################

@main.route('/shutdown')
def server_shutdown():
    """
    For acceptance testing with Selenium.
    The test_selenium.py test starts dev server on background thread while
    tests run on main thread.

    server_shutdown() gracefully shuts down the server after all test have completed
    so that coverage engine can do its thing. Because server is running
    on its own thread, only way to shutdown shut is by sending HTTP request
    This route only works in testing mode.
 
    """
    

CRUD/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
            
        <title>CRUD demo</title>
            
        <!-- CSS -->
        <!-- Using Bootstrap to provide some basic styling and UI components -->
		<!-- <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
		<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <!-- Blog -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.mycustom.css') }}">

		<!--  <link rel="stylesheet" href="{{ url_for('static', filename='css/cover.css') }}"> -->

        <!-- JavaScript -->
        <!-- jQuery -->
		<script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
		<!--vue.js-->
		<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.common.js"></script>-->
        <!-- Bootstrap -->
		<!-- <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->

		<link rel="stylesheet" href="{{ url_for('static', filename='js/bootstrap.min.js') }}"> 
    </head>
    
    <body>
        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
					</button>

					<a class="navbar-brand" href="{{ url_for('main.index') }}">Home</a>
					<a class="navbar-brand" href="{{ url_for('main.addperson') }}">Add Person</a>
					<a class="navbar-brand" href="{{ url_for('main.searchpeople') }}">Search People</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">

                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                    </ul>
                </div>
            </div>
        </div>
        <!-- calling the get_flashed_messages function, telling it to also give categories with the messages. The categories allow us to classify the severity of messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        
        <!-- block tags allow this parent template to receive content from entries.html, the child template. The block tags are like placeholders to be filled in by code from the child template(s). -->
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

CRUD/templates/index.html
{% extends "base.html" %}
{% block content %}


<br></br>
<br></br>

<div class="container">
	<div class="index-centered">
		<h1>CRUD Demo</h1>
		<p><a class="btn btn-lg btn-success" href="#" role="button">view source code</a></p>
     </div>
</div>

{% endblock %} 

CRUD/templates/searchpeople.html
<!-- The extends informs the templating engine that this template “extends” another template, base.html, establishing a link between the templates. This sends what the code below does over to base.html -->
{% extends "base.html" %}


{% block content %}

<script type="text/javascript" src="https://npmcdn.com/vue@1.0.26/dist/vue.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<div class="container" id="events">
	<a>Search by first name, last name, DOB, or postal code</a>
<br></br>
<div class="row">
	<div class="col-lg-6">
		<form action="" method="GET" id="searchForm">
			<div class="input-group">
				<input type="text" class="form-control" id="search_form_input" name="search_for" placeholder="Search for...">
				<span class="input-group-btn">
				<!-- <button class="btn btn-primary btn-outline" type="submit">Search!</button> -->
					<button type="submit" name="submit" v-on:click="searchButton($event)" class="btn btn-primary btn-outline">Search!</button>
          </span>
    </div>
</form>
</div>
</div>
<br></br>
<br></br>


	   <!-- </template> -->
   <div v-for="(index, item) in items" id="test2">

	<div class="list-group" id="entry--${ $index }">
	<!--	<template v-for="item in items" track-by="$index"> -->
	<a href="#" class="list-group-item active">
	  <b>Name:</b> ${ item.firstname} ${ item.lastname }</a>
      <a href="#" class="list-group-item"><b>DOB:</b> ${ item.dob }</a>
	  <a href="#" class="list-group-item"><b>postal code:</b> ${ item.zipcode }</a>
	  <a class="list-group-item"><button type="button" class="btn btn-danger" data-toggle="modal" id="deleteButton -- ${ $index  }" name="deleteButton -- ${ $index  }" data-target="#DeleteModal--${ $index }">DELETE</button>
		  <button type="button" class="btn btn-info" id="updateButton -- ${ $index }" name="updateButton -- ${ $index }" data-toggle="modal" data-target="#UpdateModal--${ $index }">UPDATE</button></a>
	  <br></br>
</div>
	   

<!-- DELETE Modal -->
<!-- <form action={{ url_for('main.searchpeople') }} role="form" method="POST"> -->
<form action="" role="form" method="POST" name="delete" id="delete--${$index}"> 
	<input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
	  <div class="modal fade" id="DeleteModal--${ $index }" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
		<div class="modal-content" id="del--${ $index }">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
				<h4 class="modal-title-warning" id="myModalLabel">Are you sure you want to delete this person?</h4>
				<input type="hidden" name="delete_id" value="${ item.id }" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
				<button type="submit" name="deletesubmit" v-on:click="deleteButton($index, $event)" class="btn btn-danger" >Confirm Delete</button>
				
            </div>
        </div>
    </div>
</div>
</form>


<!-- UPDATE Modal -->

<form action="" method="POST" enctype="multipart/form-data" name="updateForm" id="updateForm--${$index}">
	<!-- <form name="updateForm" id="updateForm"> -->
<input type="hidden" name="csrf_token" value="{{ csrf_token() }}" /> 	
<input type="hidden" name="vue_page_index" value="${$index}" />
<div class="modal fade" id="UpdateModal--${ $index }" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
			<div class="modal-content" id="${ $index }">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
					</button>

					<b>First name: </b><input class="form-control" type="text" name="firstname" id="${ $index }" placeholder="${ item.firstname }">
                    <b>Last Name: </b><input class="form-control" type="text" name="lastname" placeholder="${ item.lastname }">
                    <b>DOB: </b><input class="form-control" type="text" name="DOB" placeholder="${ item.dob }" >
                    <b>Postal code: </b><input class="form-control" type="text" name="zipcode" placeholder="${ item.zipcode }">
                        <input type="hidden" name="db_id" value="${ item.id }" />
					</div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
					<button type="submit" name="updatesubmit" v-on:click="updateFormButton($index, $event)" class="btn btn-success" >Save Changes</button>


                </div>
            </div>
        </div>
    </div>
</form>

<!--</template>-->

</div>



	<ul class="pager">
		<li class="previous" id="previous">
			<a href="javascript:prevPage()" id="btn_prev">Previous</a>
		</li>
		<li class="next" id="next">
			<a href="javascript:nextPage()" id="btn_next">Next</a>
		</li>
	</ul>


</div>





<script>

var itemsArray = [];

Vue.config.delimiters = ["${", "}"];

var vm = new Vue({
	//el: '#test2',
    el: '#events',
    data: {
		parentMessage: 'Parent',
		items: itemsArray
	},
	
	methods: {
		updateFormButton: function (msg, event) {
			event.preventDefault();
			updateEntry(msg, event);
		},
		deleteButton: function (msg, event){
			event.preventDefault();
			deleteEntry(msg, event);
		},
		searchButton: function(event){
			event.preventDefault();
			$("#previous").hide();
			var searchQueryCalled = true;
			queryCall(event,searchQueryCalled);
		}
		
	}

});



function updateVueInstance(itemsArray) {
	vm.items = itemsArray;
	console.log("updateVueInstance being called!!!");
	//getFormCallback();

}



// GET request to listpeople general load endpoint 
function queryCall(currentPage, searchQueryCalled) {
    var xhr = new XMLHttpRequest();
    xhr.onreadystatechange = function() {
		console.log("calling function");

		console.log(xhr.readyState);

		if(xhr.readyState == XMLHttpRequest.DONE) {
			//alert(xhr.responseText);
			//console.log(xhr.response);

		    //apiResponse = xhr.responseText;

		    apiResponse = xhr.response;
			// converting json server response string to json object
			apiResponse = JSON.parse(apiResponse);

			//console.log(apiResponse);

		    // server provides total query count for determining prev/next button visibility
		    console.log(apiResponse['results_count']);
			query_results_count = apiResponse['results_count'].length;

			//nix the results_count property from the apiResponse so we don't add a blank list item when passed to vue.js loop
	     	delete apiResponse['results_count'];
			
			itemsArray = [];

			for(var i = 0; i < apiResponse.length; i++){
				console.log(apiResponse[i]);
			}

			for (var entry in apiResponse) {
				console.log("Adding to itemsArray...")
				console.log(apiResponse[entry]);
				itemsArray.push(apiResponse[entry]);
			}
  

			console.log(itemsArray);
			updateVueInstance(itemsArray);

			// corresponds to PAGINATE_BY in views.py
			if (query_results_count <= 10){
				$("#next").hide();
				
			}

				}
	}
	
	//for search submission, not general query load
    if(searchQueryCalled){
		console.log("searchQueryCalled");
		var form = document.getElementById("searchForm");
		oData = new FormData(form);

		//var params = "?search_for="+encodeURIComponent(oData.get("search_for"));
	    searchQuery = oData.get("search_for");

	    if(currentPage > 1){
			var params =  "/page/"+encodeURIComponent(currentPage)+"?search_for="+encodeURIComponent(searchQuery);
		} else {
			var params = "?search_for="+encodeURIComponent(oData.get("search_for"));
		}

		xhr.open("GET", "/searchpeople"+params);
		//xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
	    xhr.send();



	} else {
		var params = "?page="+encodeURIComponent(currentPage);
		xhr.open("GET", "/listpeople"+params);
		//xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
	    xhr.send();
	
	}
}



var searchQuery; 

var currentPage = 1;

function nextPage() {
	currentPage++;
	console.log("currentPage number: " + currentPage);
	//currentPage = currentPage;
	if (currentPage > 1){
	    $("#previous").show();
	}
	if(searchQuery){
		console.log("next button calling searchQuery with currentpage and searchquery");
		queryCall(currentPage, searchQuery)
	} else {
		queryCall(currentPage);	
	}

}

// hide prev button on page load
if (currentPage <= 1){
	$("#previous").hide();
}


function prevPage() {
	currentPage--;
	console.log("currentPage number: " + currentPage);
	if(searchQuery){ 
		queryCall(currentPage, searchQuery)
	} else {
		queryCall(currentPage);	
	}
	if (currentPage <= 1){
	$("#previous").hide();
    }

}



// loading results on page load
window.addEventListener("load", function load(event) {
	queryCall(currentPage);
	$("#next").show();
	
});



// UDPDATE ENTRY
function updateEntry(msg, event){
	
	var indexNum = msg;
    //var form = document.getElementById("updateForm--"+indexNum);

    // jsonify update form values and elements
	var obj = {};
	var formElements = document.getElementById("updateForm--"+indexNum).querySelectorAll("input");
	for(var i = 0; i < formElements.length; ++i){
		var element = formElements[i];
		var name = element.name;
		var value = element.value;

		if(name) {
			obj[name] = value;
		}
	}

	var form = JSON.stringify(obj);
	// end jsonify form

	var oReq = new XMLHttpRequest();

	oReq.onload = function(oEvent) {
		if(oReq.status == 200) {
			console.log("DONE");
			// Bootstrap JQuery method for closing the modal after submit using Ajax
			$('#UpdateModal--'+indexNum).modal('hide');
			
			console.log("Updated db entry: " + oReq.response);
			apiResponse = JSON.parse(oReq.response);
	
			console.log("now updating vue instance....");
			var vueIndex = apiResponse['entry_vue_page_$index'];
			console.log(vueIndex);

			vm.items.$set(vueIndex, {firstname: apiResponse[vueIndex]["firstname"], lastname: apiResponse[vueIndex]["lastname"], dob: apiResponse[vueIndex]["dob"], zipcode: apiResponse[vueIndex]["zipcode"], id: apiResponse[vueIndex]["id"]});

		} else {
			console.log("There's a problem");
			console.log(oReq.status);
		}
	};
	
	//oData = new FormData(form);
	//console.log(oData.values());
    oData = form;

  oReq.open("POST", "/searchpeople", true);

  var csrftoken = "{{ csrf_token()  }}";
  oReq.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
  oReq.setRequestHeader("X-CSRFToken", csrftoken);

  oReq.send(oData);
  //event.preventDefault();

}


// DELETE entry 
function deleteEntry(msg) {

	var indexNum = msg;
	//var delForm = document.getElementById("delete--"+indexNum);

    // jsonify update form values and elements for entry to be deleted
	var obj = {};
	var formElements = document.getElementById("delete--"+indexNum).querySelectorAll("input");
	for(var i = 0; i < formElements.length; ++i){
		var element = formElements[i];
		var name = element.name;
		var value = element.value;

		if(name) {
			obj[name] = value;
		}
	}

	var form = JSON.stringify(obj);
	// end jsonify form

	var oReq = new XMLHttpRequest();

	oReq.onload = function(event){
		if(oReq.status == 200){
			console.log(JSON.parse(oReq.response));
			$('#DeleteModal--'+indexNum).modal('hide');
			$("#entry--"+indexNum).hide();
		} else {
			console.log(oReq.status);
		}
	}

	//oData = new FormData(delForm);
    oData = form;
    oReq.open("POST", "/searchpeople", true);
	var csrftoken = "{{ csrf_token()  }}";
    oReq.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
    oReq.setRequestHeader("X-CSRFToken", csrftoken);
	oReq.send(oData);
	//event.preventDefault();

}


</script>


{% endblock %}

CRUD/templates/successconfirm.html
{% block content %}


<div class="jumbotron">
  <h2>Person successfully added to the database!</h2>
    <p></p>
	  <p><a class="btn btn-primary btn-lg" href="/addperson/" role="button">Add Another Person</a></p>
	  </div>
	  </p>
</div>


{% endblock %}